repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: ./venv/bin/python -m ruff check --fix
        language: system
        types: [python]
      - id: ruff-format
        name: ruff format
        entry: ./venv/bin/python -m ruff format
        language: system
        types: [python]
